список задач по запросу
htmlacademy-php/171145-doingsdone-12 pull request #10
Opened 2021-03-31 19:03 UTC by Amaria-desveloper

2021-04-01 05:05 UTC, b1rdex requested changes
Давай делить логику на функции, на логические кусочки. Так будет проще ориентироваться в коде и index.php не будет разрастаться в объёме

2021-04-01 05:05 UTC, b1rdex commented on templates/main.php
> +                <li class="main-navigation__list-item <?php if ($_SERVER['REQUEST_URI'] === '/?project_id=' . $project['id']): ?> main-navigation__list-item--active <?php endif; ?>">
Лучше из index.php сюда передать $current_project_id и сравнивать его просто с $project['id']

2021-04-01 05:05 UTC, b1rdex commented on functions.php
> +function get_sql_result($connect, $sql_query, $data = []) {
```suggestion
function get_sql_result($connect, $sql_query, array $data = []) {
```

2021-04-01 05:05 UTC, b1rdex commented on functions.php
>  			mysqli_stmt_bind_param($stmt, "s", ...(array)$data);
```suggestion
			mysqli_stmt_bind_param($stmt, str_repeat('s', count($data)), ...$data);
```

С помощью `str_repeat('s', count($data))` будет сформирована строка ssss по количеству элементов в $data

2021-04-01 05:05 UTC, b1rdex commented on functions.php
> +function get_sql_task_result($connect, $sql_query, $data = []) {
Это можно удалить, если будет работать с str_repeat

2021-04-01 05:05 UTC, b1rdex commented on functions.php
> +function sub_array_key_exists($array, string $key, $value) {
Вызов `sub_array_key_exists($projects, 'id', (int) $project_id)` всегда будет возвращать false, т.к. в $projects все данные – строки, а для сравнения используется === с int.

Я не уверен, но мне кажется лучше эту функцию удалить и по месту писать нужную логику.

2021-04-01 05:05 UTC, b1rdex commented on index.php
> +    $project_id = filter_input(INPUT_GET, 'project_id');
Вместо это сделай переменную $current_project_id, которая будет null по-умолчанию. Ну и сразу делай её int, если она задана.

Для этого можно вообще написать функцию, которая сразу же и проверит есть ли такой проект в бд или завершит работу с 404 ошибкой.

`function get_current_project_id($connect): int {}`

2021-04-01 05:05 UTC, b1rdex commented on index.php
> +$projects = get_sql_result($connect, $sql_projects, [$current_user_id]);
Давай добавим функцию `function get_projects($connect, int $current_user_id): int`, внутрь которой перенесём sql запрос и пусть она вызывает get_sql_result

2021-04-01 05:05 UTC, b1rdex commented on index.php
> +$tasks_existence = true;
Это не нужно, можно просто проверять if($tasks) или if (count($tasks))

2021-04-01 05:05 UTC, b1rdex commented on index.php
> +        $sql_current_tasks =  "SELECT * FROM tasks WHERE user_id = ? AND project_id = ?;";
Давай добавим функцию `function get_tasks($connect, int $current_user_id, ?int $current_project_id): array`
Внутри неё пусть будут sql запросы (при вызове с проектом-int и без-null) и вызовы get_sql_task_result. Чтобы эту логику не писать снаружи.

2021-04-01 05:08 UTC, b1rdex commented on index.php
> +    $project_id = filter_input(INPUT_GET, 'project_id');
Либо внутри неё сделать `select 1 from porjects where project_id = ? and user_id = ?`, либо передай в неё $projects аргументом вместо $connect

2021-04-01 10:10 UTC, Amaria-desveloper commented on functions.php
>  			mysqli_stmt_bind_param($stmt, "s", ...(array)$data);
:tada:

2021-04-01 11:04 UTC, b1rdex commented on functions.php
>  			mysqli_stmt_bind_param($stmt, "s", ...(array)$data);
Да, ужасная функция mysqli_stmt_bind_param, очень сложная сигнатура у неё. Проще было бы для каждого параметра по 1 вызову функции сделать, чтобы отдельно указывать тип и значение.

2021-04-03 16:52 UTC, Amaria-desveloper commented
Главная вылетает с ошибкой 404, так как результат запрос = null. 
Как этого избежать? 

Может быть в `get_sql_result` делать _return mysqli_stmt_get_result($stmt);_  а потом уже в `get_projects` и `get_tasks` преобразовывать в массив?
 
И тогда в `get_current_project_id` можно проверять не циклом foreach, а сравнивать с количеством строк? (mysqli_num_rows)

2021-04-05 01:39 UTC, b1rdex requested changes

2021-04-05 01:39 UTC, b1rdex commented on templates/main.php
> +                <li class="main-navigation__list-item <?php if ((int) $current_project_id === $project['id']): ?> main-navigation__list-item--active <?php endif; ?>">
Тут (int) должно быть у $project['id'], т.к. $current_project_id уже int

2021-04-05 01:39 UTC, b1rdex commented on functions.php
> +    if(is_null($result)) {
В задании: «Если параметра нет, то показывать все задачи (как сейчас)», т.е. 404 показываем только если указан проект, которого нет в $projects. Если не указан, то просто показываем все задачи из всех проектов, а get_current_project_id возвращает null

2021-04-05 01:39 UTC, b1rdex commented on functions.php
> + * Получить список проектов по текущ
Добавь тип для $projects (array) и возвращаемый тип (?int)

2021-04-05 01:39 UTC, b1rdex commented on functions.php
> +    if(is_null($result)) {
Т.е. этот if нужно перенести внутрь if выше

2021-04-05 01:39 UTC, b1rdex commented on functions.php
> +function get_tasks($connect, int $current_user_id, int $current_project_id):array {
$current_project_id может быть null. Нужно это предусмотреть и делать запрос без `and project_id = ?` в таком случае

2021-04-05 01:41 UTC, b1rdex commented
> Главная вылетает с ошибкой 404, так как результат запрос = null.

Если я тебя правильно понял, то на это я ответил в комментарии выше – по заданию без указания проекта должны быть показаны все задачи

2021-04-05 06:29 UTC, Amaria-desveloper commented on functions.php
> +function get_tasks($connect, int $current_user_id, int $current_project_id):array {
Ааа, дошло 👍🏻

2021-04-06 06:16 UTC, b1rdex commented on functions.php
> +            if ($project['id'] === (int) $value) {
```suggestion
            if ((int)$project['id'] === (int) $value) {
```

2021-04-06 06:19 UTC, b1rdex approved these changes
Отлично 👍 
Поправил там в одном месте типы.

По show_tasks:
1. можно было внутри функции сделать логику внутри if и не делить на ещё две функции
2. это всё не show_tasks, а get_tasks. По имени show_ я бы ожидал какого-то отбражения шаблона или типа того

Не критично, можешь не исправлять

2021-04-06 06:19 UTC, merged