Module5 task1
htmlacademy-php/171145-doingsdone-12 pull request #9
Opened 2021-03-14 18:13 UTC by Amaria-desveloper

Анатолий, привет. 
Помоги, пожалуйста. По-русски, пошагово объясни, что нужно сделать.  
Синтаксис мне понятен, порядок и логику действия чтения и отображения записей не осознаю. 

Вообще хочется создать функцию и туда подставлять запросы на получение проектов и тасков. 

И не понимаю как определить текущего пользователя. Через аргумент <%юзер%> функции, или проверять $user_name? 
Мы же из queries.sql таблицу заполняем, нужно значение переменной менять динамически?

Где ошибаюсь в подключении базы через переменную? 

```
/* db.php */
<?php
$db = [
    'host' => 'localhost',
    'user' => 'root',
    'password' => 'root',
    'database' => 'doingsdone'
];

/* index.php */
$db = require_once './db.php';
$connect = mysqli_connect($db['host'], $db['user'], $db['password'], $db['database']);
```

2021-03-15 00:57 UTC, b1rdex commented on index.php
> +}
Вот это всё стоит перенести в db.php, чтобы подключение файла сразу выполняло подключение к бд, чтобы не дублировать код

2021-03-15 01:02 UTC, b1rdex commented
```
$sql_get_projects = "SELECT * FROM projects where user_id = '1'";

// следующая строка делает запрос в бд
// для select запросов она вернёт mysql_result, для других – true. При ошибках выполнения – false
$result_projects = mysqli_query($connect, $sql_get_projects);

// тут ты проверяешь не было ли ошибки при исполнении запроса
if(!$result_projects) {
    $error = mysqli_error($connect);
    print('Ошибка MySQL: ' . $error); // тут я бы поменял на die
}

// а тут ты помещаешь результат запроса в $projects
$projects = mysqli_fetch_all($result_projects, MYSQLI_ASSOC);

// данные там в такой форме:
// $projects = [
// ['id' => 1, 'user_id' => 1, 'name' => 'Первый'],
// ['id' => 2, 'user_id' => 1, 'name' => 'Второй'],
// ];
// т.е. массив массивов, каждый массив – строка из бд. Ключи – имена колонок
```

2021-03-15 01:03 UTC, b1rdex commented
> И не понимаю как определить текущего пользователя. Через аргумент <%юзер%> функции, или проверять $user_name?

Передавай аргументом функции при её вызове

2021-03-15 01:04 UTC, b1rdex commented
> Мы же из queries.sql таблицу заполняем, нужно значение переменной менять динамически?

Пока сделай просто фиксированный id, который будет совпадать с тем что в базе.

2021-03-15 21:48 UTC, Amaria-desveloper commented
$user_id = '1';
$projects = get_fetch_all($connect, "SELECT * FROM projects where user_id = '$user_id'");

Чтобы получать user_id из аргумента, нужна отдельная функция, которая возвращает конкретную заготовку запроса?

2021-03-15 21:50 UTC, Amaria-desveloper commented on templates/main.php
> +            <td class="task__date"><?= date_format(date_create($task['deadline_date']), 'd.m.Y'); ?></td>
не разобралась, как timestamp привести в нужную форму. Не пойму почему меняется порядок значений. Или в поле изначально заносить дату в другом формате?

2021-03-16 06:14 UTC, b1rdex requested changes

2021-03-16 06:14 UTC, b1rdex commented on db.php
> +}
Функцию можно удалить, просто вызывай сразу mysqli_connect напрямую, т.к. подключение будет происходить в этом же файле

2021-03-16 06:14 UTC, b1rdex commented on db.php
> +mysqli_set_charset($connect, "utf8");
Это нужно опустить ниже if, т.к. $connect тут может быть false

2021-03-16 06:14 UTC, b1rdex commented on functions.php
> +function count_tasks(array $tasks, string $project_id) : int {
А почему project_id не int?

2021-03-16 06:14 UTC, b1rdex commented on functions.php
> +        if (strval($task['project_id'] === $project_id)) {
Тут ошибка в скобочках, strval применяется к результату ===, а должно бы к $task['project_id']
Вместо strval/intval и т.д. лучше использовать приведение типов https://www.php.net/manual/ru/language.types.type-juggling.php#language.types.typecasting
Т.е. (string) вместо strval и (int) вместо intval

2021-03-16 06:14 UTC, b1rdex commented on templates/main.php
> +            <td class="task__date"><?= date_format(date_create($task['deadline_date']), 'd.m.Y'); ?></td>
htmlspecialchars можно убрать
Дата в timestamp заносится и хранится в формате 2021-03-16 16:11, а дальше её уже можно форматировать как угодно. Вроде всё получилось тут

2021-03-16 06:14 UTC, b1rdex commented on index.php
> +$tasks = get_fetch_all($connect, "SELECT * FROM tasks where user_id = '$user_id'");
Приведи сразу $user_id к int, иначе могут прикопаться к sql инъекции

2021-03-16 06:18 UTC, b1rdex commented
> $user_id = '1';
> $projects = get_fetch_all($connect, "SELECT * FROM projects where user_id = '$user_id'");
> 
> Чтобы получать user_id из аргумента, нужна отдельная функция, которая возвращает конкретную заготовку запроса?

Ну да, тут уже универсальными функциями не обойдёшься. Лучше писать под каждый запрос отдельную функцию, например
```php
function get_projects($connection, int $userId)
{
	return get_fetch_all($connection, "SELECT * FROM projects where user_id = '$user_id'");
}
```
Так ты прячешь логику получения проектов (sql запрос) внутрь функции и передаёшь туда только необходимый id пользователя.

Ещё у вас в файле https://github.com/htmlacademy-php/171145-doingsdone-12/blob/master/helpers.php#L32 есть готовая функция-обёртка для выполнения запросов с подстановкой параметров. Рекомендую разобраться в ней, т.к. большую часть запросов нужно будет делать с подстановкой параметров, чтобы избежать sql инъекций. Либо дарабатывай свою функцию get_fetch_all, чтобы в неё третьим аргументом можно было передать список параметров для подстановки :)

2021-03-21 18:43 UTC, Amaria-desveloper commented
Теперь такая проблема: 
моя функция **get_sql_result** может принять только одно значение для одного плейсхолдера, 
функция **db_get_prepare_stmt**  не принимает переменную $current_user_id. 

Возникают ошибки: 
`Warning: Invalid argument supplied for foreach() in D:\HomeServer\PHPServer\OpenServer\domains\171145-doingsdone-12\helpers.php on line 44`

`Warning: mysqli_stmt_bind_param(): Invalid type or no types specified in D:\HomeServer\PHPServer\OpenServer\domains\171145-doingsdone-12\helpers.php on line 66`

2021-03-25 06:58 UTC, b1rdex requested changes

2021-03-25 06:58 UTC, b1rdex commented on db.php
> +}
```suggestion
}

mysqli_set_charset($connect, "utf8");

```
В подобных случаях else можно не писать, т.к. в теле if будет die(), т.е. программа закончит свою работу. Соответственно, всё что за телом if будет только в случае else.

2021-03-25 06:58 UTC, b1rdex commented on data.php
> +settype($current_user_id, 'integer');
Почему не просто `$current_user_id = 1;`?

2021-03-25 06:58 UTC, b1rdex commented on functions.php
> +    } else {
Тут аналогично, else можно не писать из-за die в if

2021-03-25 06:58 UTC, b1rdex commented on functions.php
> +        mysqli_stmt_execute($stmt);
Для того чтобы твоя функция могла делать запросы с более чем 1 параметром, нужно в $data передать массив (как в db_get_prepare_stmt).
Я так понимаю warning при работе с ней у тебя был warning т.к. вызов был с передачей не массива, а просто $current_user_id.

```suggestion
		if ($data) {
			mysqli_stmt_bind_param($stmt, "s", ...(array)$data);
		}
        mysqli_stmt_execute($stmt);
```

Пишу код на гитхабе, запускать не пробовал. Надеюсь ошибки тут нет

2021-03-25 07:01 UTC, b1rdex commented
> моя функция **get_sql_result** может принять только одно значение для одного плейсхолдера,
> функция **db_get_prepare_stmt** не принимает переменную $current_user_id.

`db_get_prepare_stmt($connect, 'select * from users where user_id = ?', [$current_user_id]);`
Третий аргумент нужно передавать как массив, так работает?

Ну и выше добавил комментарий, как в твою функцию добавить возможность передавать любое количество параметров. Чтобы можно было передавать 0 параметров, нужно в сигнатуре добавить значение по-умолчанию (`$data=[]`)

2021-03-30 12:17 UTC, b1rdex commented on functions.php
> + * @param string $project_id id проекта
```suggestion
 * @param int $project_id id проекта
```

2021-03-30 12:18 UTC, b1rdex approved these changes

2021-03-30 12:18 UTC, merged